version: '3'
services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    restart: always
    environment:
      TZ: "Europe/Paris"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATIONS: "slack"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build:
      context: docker/front/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file: .env.dist
    volumes:
      - ./start:/srv/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  db:
    build:
      context: docker/pgsql
      dockerfile: Dockerfile
    volumes:
      - ./var/data:/var/lib/postgresql/data
    environment:
      POSTGRES_RO_USER: nginx
      POSTGRES_RO_PASSWORD: winners
      POSTGRES_DB: porfolio
      POSTGRES_PASSWORD: root

    deploy:
      placement:
        constraints: [node.role == manager]
